plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dushnyj.tgproxy'
    compileSdk 34

    defaultConfig {
        applicationId "com.dushnyj.tgproxy"
        minSdk 21
        targetSdk 34
        versionCode 10102
        versionName "1.1.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true
    }

    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            universalApk true
        }
    }

    signingConfigs {
        release {
            def storePath = System.getenv("ANDROID_KEYSTORE_PATH")
            if (storePath != null && !storePath.isEmpty()) {
                storeFile file(storePath)
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("ANDROID_KEY_ALIAS")
                keyPassword System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            if (System.getenv("ANDROID_KEYSTORE_PATH")) {
                signingConfig signingConfigs.release
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            applicationIdSuffix ".debug"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/BCKEY.DSA', 'META-INF/BCKEY.SF']
        }
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:-options" << "-Xlint:-deprecation"
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'org.bouncycastle:bcprov-jdk15to18:1.77'
    implementation 'com.github.mwiede:jsch:2.28.2'
    implementation 'com.google.zxing:core:3.5.3'
    implementation('com.journeyapps:zxing-android-embedded:4.3.0') {
        transitive = false
    }

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test:runner:1.5.2'
}
